---
title: "615FinalProject"
author: "Kaiyu Yan"
date: "December 11, 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggplot2)
library(plotly)
library(scales)
library(zipcode)
library(devtools)
library(mapdata)
library(ggmap)
```

```{r}
Manhattan <- read.csv("2017_manhattan.csv")
```

```{r}
Manhattan$SALE.PRICE. <- as.numeric(gsub(",","",as.character(Manhattan$SALE.PRICE.),fixed=TRUE)) 
Manhattan$LAND.SQUARE.FEET. <- as.numeric(gsub(",","",as.character(Manhattan$LAND.SQUARE.FEET.),fixed=TRUE))
Manhattan$GROSS.SQUARE.FEET. <- as.numeric(gsub(",","",as.character(Manhattan$GROSS.SQUARE.FEET.),fixed=TRUE))
Manhattan$SALE.DATE. <- as.Date(Manhattan$SALE.DATE.,"%m/%d/%Y")
```

```{r}
ggplot(Manhattan)+
   geom_bar(mapping = aes(x = NEIGHBORHOOD.))+
   theme(axis.text.x = element_text(angle = 45, hjust = 1))



Midtown <- filter(Manhattan,str_detect(Manhattan$NEIGHBORHOOD., "MIDTOWN"))
A <- ggplot(Midtown,aes(NEIGHBORHOOD., fill =BUILDING.CLASS.AT.TIME.OF.SALE.)) +
        geom_bar(position = "fill") +
      
        xlab ("Categories") +
        ylab("Percentage") + 
        theme(axis.text.x = element_text(size = 12, angle =45, hjust = 1)) + 
        guides(fill=guide_legend(title="Answers"))
ggplotly(A)


Midtown$Month <- as.Date(cut(Midtown$SALE.DATE.,
  breaks = "month"))

Manhattan$Month <- as.Date(cut(Manhattan$SALE.DATE.,
  breaks = "month"))

ggplot(data = Manhattan,
  aes(Month, SALE.PRICE.)) +
  stat_summary(fun.y = sum, # adds up all observations for the month
    geom = "bar") + # or "line"
  scale_x_date(labels = date_format("%Y-%m"), breaks = "1 month") +# custom x-axis labels
 theme(axis.text.x = element_text(angle =60, hjust = 1))

ggplot(data = Manhattan,
  aes(NEIGHBORHOOD., SALE.PRICE.)) +
  scale_y_continuous(labels = comma)+
  stat_summary(fun.y = sum, # adds up all observations for the month
    geom = "bar") + # or "line"
   theme(axis.text.x = element_text(angle =60, hjust = 1))

ggplot(data = Manhattan,
  aes(NEIGHBORHOOD., SALE.PRICE.)) +
  scale_y_continuous(labels = comma)+
  stat_summary(fun.y = median, # adds up all observations for the month
    geom = "bar") + 
   theme(axis.text.x = element_text(angle =60, hjust = 1))

ggplot(data = Manhattan,
  aes(NEIGHBORHOOD., SALE.PRICE.)) +
  scale_y_continuous(labels = comma)+
  stat_summary(fun.y = mean, # adds up all observations for the month
    geom = "bar") + 
   theme(axis.text.x = element_text(angle =60, hjust = 1))

ggplot(data = Midtown,
  aes(Month, fill = NEIGHBORHOOD.)) +
   theme(axis.text.x = element_text(angle =60, hjust = 1))+
   geom_bar(position = "dodge")

p <-  Midtown%>%
  filter(SALE.PRICE.<2210000000) %>% ggplot( aes(GROSS.SQUARE.FEET., SALE.PRICE., size = SALE.PRICE., color=NEIGHBORHOOD.)) +
  geom_point() +
  scale_y_continuous(labels = comma)+
    theme_bw()
ggplotly(p)



```

```{r}
library(benford.analysis)
bfd <- benford(Manhattan$SALE.PRICE.)
plot(bfd)
bfd
suspects <- getSuspects(bfd, Manhattan)
suspects
```

```{r}
data("zipcode")
```

```{r}
data("zipcode")
colnames(Manhattan)[11] <- "zip"
Manhattan$zip <- as.character(Manhattan$zip)
Manhattan_zip <- inner_join(Manhattan,zipcode,by="zip")
Manhattan_zip$latitude <- as.numeric(Manhattan_zip$latitude)
Manhattan_zip$longitude <- as.numeric(Manhattan_zip$longitude)
Ne_sum <- aggregate(SALE.PRICE.~NEIGHBORHOOD.,data = Manhattan_zip,sum)

ASDF <- inner_join(Ne_sum, Manhattan_zip,by = "NEIGHBORHOOD.")
ASDF <- distinct(ASDF,NEIGHBORHOOD.,.keep_all = TRUE)
library(leaflet)
m <- leaflet(data =ASDF ) %>%
  addTiles() %>%  # Add default OpenStreetMap map tiles
  addMarkers( ~longitude,~latitude
, popup = ~as.character(SALE.PRICE..x), label = ~as.character(NEIGHBORHOOD.))
m  # Print the map
```